@startuml "Venta"

skinparam noteBackgroundColor transparent
skinparam noteBorderColor transparent
hide members

object ": Actor" as User
object ": Registro" as Register
object ": Venta" as Sale
object ": CatalogoProductos" as Catalogue
object ": Lineaventa" as SaleLine
object ": List" as List


User -r-> Register
note on link
    introducirArticulo()
end note

Register -d-> Catalogue
note on link
    1: getEspecificacion(id)
end note


Register -r-> Sale
note on link
    2: crearLineaVenta(espec, id) 
end note

Sale -r-> List
note on link
    4: añadir(new LineaVenta(espec, cant))
end note

Sale --> SaleLine
note on link
    3: new ArrayList()
end note

@enduml
